### ISSUE TITLE
Offset when changing source

### ISSUE THREAD

**Issue by sbauch** [dogusdigital/videojs-time-offset#5]
Have been trying to figure out a way to make this plugin apply new offsets when I change the source. Haven't had much luck.

The plugin runs it's offsetting primarily in the onReady block. I'm a bit surprised that videojs doesn't trigger the ready event when a new source is loaded, but even calling `player.triggerReady()` didn't seem to help.

Here's a quick code example. It's a react app, but generally this is the block I run when I want to change to a different video - 

```js
      this.player.src(newProps.nugget.assetUrl);

      this.player.timeOffset({
        start: newProps.nugget.timestampStart,
        end: newProps.nugget.timestampEnd,
      });


      this.player.triggerReady();
```

What ends up happening is that subsequent tracks play from the beginning with the same custom duration as the first video. 

The first video is offset as expected, this is the setup code:

```js
  this.player = videojs(this.videoNode, props, () => {
      console.log('player ready')
    });

    this.player.timeOffset({
      start: nugget.timestampStart,
      end: nugget.timestampEnd,
    });
```

Any ideas?

**Comment by kuehn-sba** [comment]
Hey,

add extra function to player in videojs-time-offset:

```
  player.updateTimeOffset = function(start, end) {
    offsetStart       = start;
    offsetEnd         = end;
    computedDuration  = offsetEnd - offsetStart;
  };
```

Call this function only once for the first source:
`player.timeOffset({start: x, end: y });`

and then use the following call for all other source changes:
`player.updateTimeOffset(start: newx, end: newy );`

**Comment by sbauch** [comment]
ah interesting, thank you!

I ended up using media fragments. Although not supported by IE, this is for an internal piece of software so I don't feel so bad about not supporting IE.
